src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>auActivityRelated__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>auActivityRelated</label>
        <referenceTo>auActivityRelated__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/auActivityRelated__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentsFromEvent__c</fullName>
        <label>活動添付ファイル</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsHaveAttachmentFromEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>活動添付ファイル有無</label>
        <type>Checkbox</type>
    </fields>
    <label>auActivityRelated</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>イベント報告用のレコードタイプ</description>
        <label>イベント報告</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/updateHasAttachmentForEventRelated.cls
global class updateHasAttachmentForEventRelated implements Database.Batchable<sObject> {
	
	String query = 'SELECT AttachmentsFromEvent__c, IsHaveAttachmentFromEvent__c,  (SELECT Id FROM Activities__r) FROM auActivityRelated__c';
	
	global updateHasAttachmentForEventRelated() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<auActivityRelated__c> scope) {
		List<auActivityRelated__c> updateList = new List<auActivityRelated__c>();
		Map<Id, auActivityRelated__c> mapEventIds = new Map<Id, auActivityRelated__c>();
		for(auActivityRelated__c re : scope){
		    if (re.Activities__r != null && re.Activities__r.size() > 0){
		        mapEventIds.put(re.Activities__r[0].Id, re);
		    }
		}
		List<Id> eventIds = new List<Id>(mapEventIds.keySet());
		List<Event> evs = [SELECT Id, (SELECT Id FROM Attachments) FROM Event WHERE Id IN : eventIds];
		for(Event ev : evs) {
			if(ev.Attachments != null && ev.Attachments.size() > 0) {
				auActivityRelated__c re = mapEventIds.get(ev.Id);
				List<Id> eventAtts = new List<Id> ((new Map<Id, Attachment>(ev.Attachments)).keySet());
				re.AttachmentsFromEvent__c = String.join(ev.Attachments, ';');
				re.IsHaveAttachmentFromEvent__c = true;
				updateList.add(re);
			}
		}
		update updateList;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}