src/objects/auCommunityCustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>auCommunityCustomSettings</label>
</CustomObject>

src/objects/auCXKnowledge__c.object
<CustomObject>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CreatedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>auCXKnowledge_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DisplayedDate__c</fullName>
        <label>DisplayedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TemporarySaved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NationalApproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CXナレッジ</label>
    <nameField>
        <displayFormat>CX-{00000000}</displayFormat>
        <label>CXナレッジ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/auCXKnowledgeListCSVExportingCtrlTest.cls
@isTest
private class auCXKnowledgeListCSVExportingCtrlTest {
	
	private static auCXKnowledge__c createCxKnowledge(Id userId){
		auCommunityCustomSettings__c setting = auTestDataUtil.createCustomSettingHasUserIDOwnerCX();
		auCXKnowledge__c cx = new auCXKnowledge__c();
		cx.DisplayedDate__c = DateTime.now();
		cx.Status__c = auConstantCmn.CX_KNOWLEDGE_STATUS_SAVED;
		cx.Title__c = 'test';
		cx.CreatedBy__c = userId;
		insert cx;
		FeedItem feed = new FeedItem();
		feed.ParentId = cx.Id;
		feed.Body = 'test';
		insert feed;
		//auUtilChatter.postCommentToFeedElement(feed.Id, 'test');
		//ConnectApi.ChatterLike chatterLike = ConnectApi.ChatterFeeds.likeFeedElement(null, feed.Id);
		return cx;
	}

	@isTest static void test_Constructor() {
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.standarduser@ezweb.ne.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');

        System.runAs(u) {
        	auCXKnowledge__c cx = createCxKnowledge(u.Id);
        	
        	Test.startTest();
        	Test.setCurrentPageReference(new PageReference('auCXKnowledgeListCSVExporting'));
			System.currentPageReference().getParameters().put('where', ' WHERE Id = \'' + cx.Id + '\'');
			auCXKnowledgeListCSVExportingCtrl ctrl = new auCXKnowledgeListCSVExportingCtrl();

			System.currentPageReference().getParameters().put('filter', 'test');
			ctrl = new auCXKnowledgeListCSVExportingCtrl();

			system.assertNotEquals('', ctrl.sTitle);
			Test.stopTest();
        }
	}
	
}