src/objects/auEvent__c.object
<CustomObject>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>auEvent_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsFinished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>完了</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Kickoff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMeeting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>OwnerMeeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>イベント</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/auEventsListCSVExportCtrlTest.cls
@isTest
private class auEventsListCSVExportCtrlTest {
	
	private static auEvent__c createEvent(Id userId){
		auEvent__c e = new auEvent__c();
		e.EventDate__c = Date.today();
		for (Schema.PicklistEntry f : auEvent__c.Type__c.getDescribe().getPicklistValues()) {
            e.Type__c = f.getValue();
            break;
        }
		e.IsFinished__c = true;
		e.EventName__c = 'test';
		e.CreatedBy__c = userId;
		insert e;
		return e;
	}

	@isTest static void test_Constructor() {
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.standarduser@ezweb.ne.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');

        System.runAs(u) {
        	auEvent__c e = createEvent(u.Id);
        	
        	Test.startTest();
        	Test.setCurrentPageReference(new PageReference('auEventsListCSVExport'));
			System.currentPageReference().getParameters().put('olddata', '1');
			auEventsListCSVExportCtrl ctrl = new auEventsListCSVExportCtrl();

			system.assertNotEquals('', ctrl.sTitle);
			Test.stopTest();
        }
	}
	
}