src/objects/auHonbuDirect__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>カテゴリ</label>
        <picklist>
            <picklistValues>
                <fullName>CAT1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT3</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ImplementationEndDate__c</fullName>
        <label>実施終了日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ImplementationStartDate__c</fullName>
        <label>実施開始日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>タイトル</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransmissionDate__c</fullName>
        <label>発信日時</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>auチャンネル</label>
    <nameField>
        <displayFormat>HD-{00000000}</displayFormat>
        <label>auHonbuDirect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/auHonbuDirectCtrlTest.cls
@isTest
private class auHonbuDirectCtrlTest {

	@isTest
    static void test_research() {
    	User adminUser = auTestDataUtil.createAdminUser('admin');

    	System.runAs(adminUser) {

    		Test.setCurrentPageReference(new PageReference('Page.auHonbuDirectPage'));
    		ApexPages.currentPage().getHeaders().put('USER-AGENT', '... internet explorer ...');

    		auHonbuDirectCtrl ctrl = new auHonbuDirectCtrl();

    		//ctrl.lsHonbuDirect = new List<ctrl.clsHonbuDirect>();
    		System.assertEquals(ctrl.lsHonbuDirect.size(),0);
    		
    		auHonbuDirect__c source = createHonbuDirect();
    		
    		ctrl.filterFreeWord='Honbu';
    		ctrl.filterCategory='CAT1';
    		ctrl.isNewOnly=true;
    		ctrl.isNotRepliedOnly=true;

    		ctrl.searchData();
    		
    		System.Assert(ctrl.lsHonbuDirect.size()>=1);
    		
    		ctrl.currentHonbuDirectId=source.Id;
    		
    		ctrl.showCurrentHonbuDirect();
    	}
    }
    
    @isTest
    static void test_readAndFavorite() {
    	User adminUser = auTestDataUtil.createAdminUser('admin');

    	System.runAs(adminUser) {

    		Test.setCurrentPageReference(new PageReference('Page.auHonbuDirectPage'));
    		ApexPages.currentPage().getHeaders().put('USER-AGENT', '... internet explorer ...');
    		
    		auHonbuDirectCtrl ctrl = new auHonbuDirectCtrl();
    		
    		auHonbuDirect__c source = createHonbuDirect();

    		ctrl.currentHonbuDirectId=source.Id;
    		
    		ctrl.showCurrentHonbuDirect();
    		
    		ctrl.currentHonbuDirect.isRead=false;
    		ctrl.currentHonbuDirect.isFavorite=false;
    		
    		ctrl.currentHonbuDirect.addToRead();
			System.assertEquals(ctrl.currentHonbuDirect.isRead,true);
			ctrl.currentHonbuDirect.addToFavorite();
			System.assertEquals(ctrl.currentHonbuDirect.isFavorite,true);
			ctrl.currentHonbuDirect.removeFromFavorite();
			System.assertEquals(ctrl.currentHonbuDirect.isFavorite,false);
    	}
    }
    
    @isTest
    static void test_showCurrent() {
    	User adminUser = auTestDataUtil.createAdminUser('admin');

    	System.runAs(adminUser) {

    		Test.setCurrentPageReference(new PageReference('Page.auHonbuDirectPage'));
    		ApexPages.currentPage().getHeaders().put('USER-AGENT', '... internet explorer ...');
    		
    		auHonbuDirectCtrl ctrl = new auHonbuDirectCtrl();
    		
    		auHonbuDirect__c source = createHonbuDirect();

    		ctrl.currentHonbuDirectId=source.Id;
    		
    		ctrl.showCurrentHonbuDirect();
    	}
    }
    
    public static auHonbuDirect__c createHonbuDirect(){
		auHonbuDirect__c honbuDirect = new auHonbuDirect__c();
		honbuDirect.Title__c = 'Honbu Direct Test';
		honbuDirect.Category__c = 'CAT1';
		DateTime auHonbuDirectDateTime = datetime.now();
		honbuDirect.TransmissionDate__c = auHonbuDirectDateTime;
		Date auHonbuDirectDate = date.today();
		honbuDirect.ImplementationStartDate__c = auHonbuDirectDate;
		honbuDirect.ImplementationEndDate__c = auHonbuDirectDate.addDays(7);
		insert honbuDirect;
		return honbuDirect;
	}
	
}