src/objects/auHonbuDirect__c.object
<CustomObject>
    <label>auチャンネル</label>
    <nameField>
        <displayFormat>HD-{00000000}</displayFormat>
        <label>auHonbuDirect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/auHonbuDirectDetail__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>VIEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>READ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAVORITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KDDI_ACCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA_ACCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SHOP_ACCESS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>auHonbuDirectDetail_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>auHonbuDirectKDDI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>auチャネルKDDI</label>
        <referenceTo>auHonbuDirect__c</referenceTo>
        <relationshipName>auHonbuDirectDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>auHonbuDirectSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>auチャネルSA</label>
        <referenceTo>auHonbuDirect__c</referenceTo>
        <relationshipName>auHonbuDirectDetailSA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>auHonbuDirectShop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>auチャネルShop</label>
        <referenceTo>auHonbuDirect__c</referenceTo>
        <relationshipName>auHonbuDirectDetail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>auHonbuDirect__c</fullName>
        <label>auチャネル</label>
        <referenceTo>auHonbuDirect__c</referenceTo>
        <relationshipName>auHonbuDirectDetail_MD</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>auチャンネル詳細</label>
    <nameField>
        <displayFormat>HDD-{00000000}</displayFormat>
        <label>auHonbuDirectDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/auAddUserWithoutSharing.cls
public without sharing class auAddUserWithoutSharing {
    
    public static void addAllCorrespondingUsers(Set<Id> newIds,String sourceId,String pageType) {
       	system.debug('Run: addAllCorrespondingUsers');

        List<auHonbuDirectDetail__c> newDetails = new List<auHonbuDirectDetail__c>();
        List<auHonbuDirect__share> listOfPerm = new List<auHonbuDirect__share>();
        for(Id newId : newIds){
        	auHonbuDirectDetail__c newDetail = new auHonbuDirectDetail__c();
			newDetail.auHonbuDirect__c=sourceId;

			auHonbuDirect__share perm = new auHonbuDirect__share();
			perm.ParentId = sourceId;
			perm.userOrGroupId = newId;

			//TODO ChangeType
			newDetail.Type__c = pageType;
			newDetail.User__c = newId;
			if(pageType==auConstantCmn.ACCESS_TYPE_SA){
				newDetail.auHonbuDirectSA__c=sourceId;
				perm.RowCause = Schema.auHonbuDirect__share.RowCause.shared_To_This_SA_User__c;
			}
			if(pageType==auConstantCmn.ACCESS_TYPE_KDDI){
				newDetail.auHonbuDirectKDDI__c=sourceId;
				perm.RowCause = Schema.auHonbuDirect__share.RowCause.shared_To_This_KDDI_User__c;
			}
			if(pageType==auConstantCmn.ACCESS_TYPE_SHOP){
				newDetail.auHonbuDirectShop__c=sourceId;
				perm.RowCause = Schema.auHonbuDirect__share.RowCause.shared_To_This_Shop_User__c;
			}
			perm.AccessLevel = 'Read';
			listOfPerm.add(perm);
			newDetails.add(newDetail);
        }
        system.debug('before insert Limits.getCpuTime(): ' + Limits.getCpuTime());
		//Insert the new users
		insert(newDetails);
		
		insert listOfPerm;  
		system.debug('finish Limits.getCpuTime(): ' + Limits.getCpuTime());  
	}
    
}