src/objects/auSurvey__c.object
<CustomObject>
    <fields>
        <fullName>RegionalOfficeName__c</fullName>
        <label>支社</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>surveyId__c</fullName>
        <formula>CASESAFEID( User__c ) + FiscalYear__c + TEXT(Period__c) + Title__c</formula>
        <label>surveyId</label>
        <type>Text</type>
    </fields>
    <label>auSurvey</label>
    <nameField>
        <displayFormat>AUS-{00000000}</displayFormat>
        <label>auSurvey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/saTelemarketing__c.object
<CustomObject>
    <fields>
        <fullName>AffiliationCode__c</fullName>
        <label>加入者CD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AffiliationDate__c</fullName>
        <label>加入者生年月日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AppearanceCleanliness__c</fullName>
        <label>身だしなみの清潔感</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationNumber__c</fullName>
        <externalId>true</externalId>
        <label>申込番号</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BusinessLocationCode__c</fullName>
        <label>拠点CD</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessLocationName__c</fullName>
        <label>拠点名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargeExplanation__c</fullName>
        <label>使い方にあった料金の説明提案</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cordiality__c</fullName>
        <label>親身に聞いていたか</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CorrespondenceCompletionDate__c</fullName>
        <label>対応完了期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CorrespondenceDate__c</fullName>
        <label>初回架電対応期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EvolutionDate__c</fullName>
        <label>展開日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Greeting__c</fullName>
        <label>挨拶</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InformationExplanation__c</fullName>
        <label>知識理解度に応じた分かりやすい説明</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>オーダ日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderType__c</fullName>
        <label>オーダ種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OtherProblemInquiry__c</fullName>
        <label>他に何か相談,困りごとがないかお伺い</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneServiceAdvice__c</fullName>
        <label>電話機サービスの便利な使い方アドバイス</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Q1_ShopRecommendationTime__c</fullName>
        <label>Q1店舗推奨度</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q2_1_RecommendationReason__c</fullName>
        <label>Q2-1勧めたい理由</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Q2_2_NoRecommendationReason__c</fullName>
        <label>Q2-2勧めたくない理由</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Q3_StaffCorrespondence__c</fullName>
        <label>Q3スタッフの対応</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionalOfficeName__c</fullName>
        <label>支社</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyDate__c</fullName>
        <label>回答日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShopNoticeContent__c</fullName>
        <label>（ショップ）掲示内容</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShopSanitaryPrecautions__c</fullName>
        <label>（ショップ）店内の清潔さ・整理整頓</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smiling__c</fullName>
        <label>笑顔</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpeechAttitude__c</fullName>
        <label>言葉遣い・態度</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StaffName__c</fullName>
        <label>スタッフ氏名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <summarizedField>saTelemarketingReply__c.StatusInt__c</summarizedField>
        <summaryForeignKey>saTelemarketingReply__c.Parent__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>VoiceTiming__c</fullName>
        <label>お声がけ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WaitingTimeConsideration__c</fullName>
        <label>待ち時間気遣い</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WaitingTimeInfo__c</fullName>
        <label>待ち時間案内</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>saTelemarketing</label>
    <nameField>
        <displayFormat>TLM-{00000000}</displayFormat>
        <label>saTelemarketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/saTelemarketingReply__c.object
<CustomObject>
    <fields>
        <fullName>AffiliationCode__c</fullName>
        <label>加入者コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentCode__c</fullName>
        <label>応対内容コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthForSearch__c</fullName>
        <label>検索用年月</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>saTelemarketing__c</referenceTo>
        <relationshipLabel>saTelemarketingReply</relationshipLabel>
        <relationshipName>saTelemarketingReply</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReceptionDate__c</fullName>
        <label>受付年月日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReceptionDatetime__c</fullName>
        <label>受付日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>応対内容</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>対応結果コード</label>
        <picklist>
            <picklistValues>
                <fullName>T0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T7</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>saTelemarketingReply</label>
    <nameField>
        <displayFormat>TLMR-{00000000}</displayFormat>
        <label>saTelemarketingReply Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Hierarchical_Code_1__c</fullName>
        <label>Hierarchical Code 1</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_3__c</fullName>
        <label>第3階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_4__c</fullName>
        <label>第4階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_5__c</fullName>
        <label>第5階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/kdTelemarketingListCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class kdTelemarketingListCtrlTest {

    private static saTelemarketing__c createTelemarketing(){
		saTelemarketing__c telema = new saTelemarketing__c();
		telema.Q1_ShopRecommendationTime__c = 123;
		telema.Q2_1_RecommendationReason__c = 'Test';
		telema.Q2_2_NoRecommendationReason__c = 'Test';
		telema.Q3_StaffCorrespondence__c = 'Test';
		telema.BusinessLocationCode__c = 'Test';
		telema.BusinessLocationName__c = 'Test';
		telema.StaffName__c = 'Test';
		telema.ReplyDate__c = Date.Today();
		telema.OrderDate__c = Date.Today();
        telema.EvolutionDate__c = Date.Today();
        telema.OrderType__c = 'Test';
        telema.ApplicationNumber__c = 'Test';
        telema.AffiliationCode__c = 'Test';
        telema.AffiliationDate__c = Date.Today();
        telema.CorrespondenceDate__c = Date.Today();
        telema.ShopSanitaryPrecautions__c = 'Test';
        telema.ShopNoticeContent__c = 'Test';
        telema.VoiceTiming__c = 'Test';
        telema.WaitingTimeInfo__c = 'Test';
        telema.WaitingTimeConsideration__c = 'Test';
        telema.Greeting__c = 'Test';
        telema.Smiling__c = 'Test';
        telema.AppearanceCleanliness__c = 'Test';
        telema.SpeechAttitude__c = 'Test';
        telema.Cordiality__c = 'Test';
        telema.InformationExplanation__c = 'Test';
        telema.ChargeExplanation__c = 'Test';
        telema.PhoneServiceAdvice__c = 'Test';
        telema.OtherProblemInquiry__c = 'Test';
        telema.RegionalOfficeName__c = 'Test';
        telema.CorrespondenceCompletionDate__c = Date.Today();
		
		insert telema;
		return telema;
	}

	private static saTelemarketingReply__c createTelemarketingReply(Id id){
		saTelemarketingReply__c telemaReply = new saTelemarketingReply__c();
		telemaReply.Parent__c = id;
		telemaReply.Result__c = '123';
		telemaReply.ContentCode__c = 'Test';
		telemaReply.AffiliationCode__c = 'Test';
		telemaReply.MonthForSearch__c = Date.Today();
		telemaReply.ReceptionDatetime__c = Datetime.now();
		telemaReply.ReceptionDate__c = Date.Today();
		telemaReply.Status__c = 'T0';
		
		insert telemaReply;
		return telemaReply;
	}

    @isTest(SeeAllData=true) 
    static void searchTest1() {
		
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.test1@kddi.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='tremy1@kddi.com', Hierarchical_Code_1__c='010K0J',
            Hierarchical_Label_3__c='Label3',Hierarchical_Label_4__c='Label4',Hierarchical_Label_5__c='Label5');
	    	
	    insert u;  
		System.runAs(u) {   
		    	
		    	/*auSurvey__c survey = createSurvey('職場サーベイ',999,'',1,'','',u.Id,false);
		    	survey = [select Id,surveyId__c From auSurvey__c where Id= :survey.Id];
			    for(Integer i=1;i<=12;i++){   
			        createSurvey('職場サーベイ',i,'Test'+String.valueOf(Math.floor(i/2)),0,'','',u.Id,false);
			    }
			    createSurvey('職場サーベイ',19,'',1,'Test19-1','Test19-1',u.Id,true);
			    createSurvey('職場サーベイ',19,'',2,'Test19-2','Test19-2',u.Id,true);
			    createSurvey('職場サーベイ',20,'',1,'Test20-1','Test20-1',u.Id,true);
			    createSurvey('職場サーベイ',20,'',2,'Test20-2','Test20-2',u.Id,true);*/
		    	 
				PageReference pageRef = Page.kdTelemarketingListPage;
				Test.setCurrentPage(pageRef);
				ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');
	        
	        	saTelemarketing__c telema = createTelemarketing();
	        	kdTelemarketingListCtrl ctrl = new kdTelemarketingListCtrl();
	        	ctrl.telemaUpdateId = telema.id;
	        	saTelemarketingReply__c telemaReply = createTelemarketingReply(telema.id);
	        
	        	//kdTelemarketingListCtrl ctrl = new kdTelemarketingListCtrl();
	        	ctrl.clearCookie();
	        	ctrl.doSearch();
	        	ctrl.filterReplyDateFromStr = '2019/01/01';
	        	ctrl.filterReplyDateToStr = '3019/01/01';
	        	ctrl.filterOrderDateFromStr = '2019/01/01';
	        	ctrl.filterOrderDateToStr = '3019/01/01';
	        	ctrl.filterEvolutionDateFromStr = '2019/01/01';
	        	ctrl.filterEvolutionDateToStr = '3019/01/01';
	        	ctrl.filterCorrespondenceDateFromStr = '2019/01/01';
	        	ctrl.filterCorrespondenceDateToStr = '3019/01/01';
	        	ctrl.getRecords();
	        	ctrl.doSearch();
	        	ctrl.getListShisha();
	        	ctrl.getListMonths();
	        	ctrl.getListShiten();
	        	ctrl.changeReplyDate();
	        	ctrl.refreshTelemaEdit();
	        	ctrl.setSizeSaveCurrentPageSize();
	        	ctrl.changeOrder();
	        	ctrl.goToPage1();
				ctrl.goToPage2();
				ctrl.goToPage3();
				ctrl.goToPage4();
				ctrl.goToPage5();
				ctrl.goToPage6();
				ctrl.goToPage7();
				ctrl.goToPage8();
				//ctrl.goToPageNext();
				//ctrl.goToPagePrev();
				ctrl.goToPage2ndNext();
				ctrl.goToPageLast();
				//ctrl.goToPageLastBfr1();
				//ctrl.goToPageLastBfr2();
				//ctrl.goToPageLastBfr3();
				//ctrl.goToPageLastBfr4();
				//ctrl.goToPageLastBfr5();
	        	
	        	//ctrl.surveyUpdateId=survey.surveyId__c;
	        	//ctrl.getSurveyDetails();
	    }

	}
}