src/objects/kdGpsTracking__c.object
<CustomObject>
    <fields>
        <fullName>Datetime__c</fullName>
        <label>Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GPSTracking_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GPSトラッキング</label>
    <nameField>
        <displayFormat>GT-{0000000000}</displayFormat>
        <label>GPSトラッキング Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/auCustomRestService.cls
@RestResource(urlMapping='/GpsTracking/*')
global without sharing class auCustomRestService {
    
     @HttpPost
	global static void doPost(String User, DateTime LocationDateTime, Double latitude, Double longitude) {
		
		//APEX code goes here to query and create records
		kdGpsTracking__c newGPSData = new kdGpsTracking__c();
		newGPSData.Datetime__c=LocationDateTime;
		newGPSData.GeoLocation__latitude__s=latitude;
		newGPSData.GeoLocation__longitude__s=longitude;
		newGPSData.User__c=User;
		insert(newGPSData);
		
    }
    
}