src/objects/kdKnowledge__c.object
<CustomObject>
    <fields>
        <fullName>DentouiriFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>殿堂入りフラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <label>LastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MediumCategory__c</fullName>
        <label>MediumCategory</label>
        <picklist>
            <controllingField>Thema__c</controllingField>
            <picklistValues>
                <fullName>cate1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cate8</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecommendFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>事務局おすすめ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thema__c</fullName>
        <label>Thema</label>
        <picklist>
            <picklistValues>
                <fullName>Val1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Val5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Val28</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Value1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Value2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value9</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UpdateModificationDateTime__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdateModificationDateTime</label>
        <type>Checkbox</type>
    </fields>
    <label>営業ナレッジ</label>
    <nameField>
        <displayFormat>EK-{00000000}</displayFormat>
        <label>営業ナレッジ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/kdKnowledgeTriggerTest.cls
@isTest
private class kdKnowledgeTriggerTest {
	
	private static kdKnowledge__c createKnowledge(){
		kdKnowledge__c k = new kdKnowledge__c();
		k.Thema__c = 'Val6';
		k.RecommendFlag__c = true;
		k.DentouiriFlag__c = true;
		k.MediumCategory__c = 'CX・ES';
		k.Type__c = 'Value1';
		k.Title__c = 'Test';
		k.UpdateModificationDateTime__c = true;
		k.LastModifiedDate__c = Datetime.now();
		insert k;
		return k;
	}
	
	@isTest static void test_method() {
		kdKnowledge__c k1 = createKnowledge();
		system.debug('k1: ' + k1);
		system.assertEquals(true, k1.UpdateModificationDateTime__c);
	}
	
}