src/objects/saBusinessLocation__c.object
<CustomObject>
    <fields>
        <fullName>AgencyCode__c</fullName>
        <label>代理店コード</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyName__c</fullName>
        <label>代理店名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessLocationName__c</fullName>
        <label>BusinessLocationName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SupervisorCode__c</fullName>
        <label>統括店コード</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupervisorName__c</fullName>
        <label>統括店名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>拠点</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>saBusinessLocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/saBusinessLocationMembers__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLocation__c</fullName>
        <label>拠点</label>
        <referenceTo>saBusinessLocation__c</referenceTo>
        <relationshipLabel>拠点詳細</relationshipLabel>
        <relationshipName>saBusinessLocationDetail_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>拠点種別</label>
        <picklist>
            <picklistValues>
                <fullName>PRINCIPAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARY</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>saBusinessLocationDetail_user</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>拠点詳細</label>
    <nameField>
        <displayFormat>BLM-{00000000}</displayFormat>
        <label>拠点詳細 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/saInquiry__c.object
<CustomObject>
    <fields>
        <fullName>ReportName__c</fullName>
        <label>フォーム名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>TemporarySaved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>DAILY_REPORT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SURVEY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU_HEARING</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidFrom__c</fullName>
        <label>運用From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ValidTo__c</fullName>
        <label>運用To</label>
        <type>Date</type>
    </fields>
    <label>問い合わせ</label>
    <nameField>
        <displayFormat>INQ-{00000000}</displayFormat>
        <label>問い合わせ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/saInquiryDetail__c.object
<CustomObject>
    <fields>
        <fullName>AnswerType__c</fullName>
        <label>AnswerType</label>
        <picklist>
            <picklistValues>
                <fullName>TEXT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NUMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DECIMAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RADIO_BUTTON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHECKBOX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERIOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LABEL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NumberPossibleReplies__c</fullName>
        <label>NumberPossibleReplies</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>QuestionLabel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply01Label__c</fullName>
        <label>Reply01Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply02Label__c</fullName>
        <label>Reply02Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>SortNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>saInquiry__c</fullName>
        <label>問い合わせ</label>
        <referenceTo>saInquiry__c</referenceTo>
        <relationshipLabel>問い合わせ詳細</relationshipLabel>
        <relationshipName>saInquiryDetail_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>問い合わせ詳細</label>
    <nameField>
        <displayFormat>INQD-{00000000}</displayFormat>
        <label>問い合わせ詳細 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/saInquiryReply__c.object
<CustomObject>
    <fields>
        <fullName>DailyReportDate__c</fullName>
        <description>For Daily Report application, for which day is the current Daily Report?</description>
        <label>日報日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>WAITING_REPLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_SAVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_SENT</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>saInquiryReply_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>saBusinessLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>拠点</label>
        <referenceTo>saBusinessLocation__c</referenceTo>
        <relationshipLabel>問い合わせ返事</relationshipLabel>
        <relationshipName>saInquiryReply_saBusinessLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>saInquiry__c</fullName>
        <label>問い合わせ</label>
        <referenceTo>saInquiry__c</referenceTo>
        <relationshipLabel>問い合わせ返事</relationshipLabel>
        <relationshipName>saInquiryReply_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>問い合わせ返事</label>
    <nameField>
        <displayFormat>INQR-{00000000}</displayFormat>
        <label>問い合わせ返事 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/saInquiryReplyDetail__c.object
<CustomObject>
    <fields>
        <fullName>ReplyCheckbox01__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reply (Checkbox) 01</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReplyCheckbox02__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reply (Checkbox) 02</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReplyRadioButton__c</fullName>
        <label>Reply (Radio Button)</label>
        <picklist>
            <picklistValues>
                <fullName>REPLY_01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>saInquiryDetail__c</fullName>
        <label>問い合わせ詳細</label>
        <referenceTo>saInquiryDetail__c</referenceTo>
        <relationshipLabel>問い合わせ返事詳細</relationshipLabel>
        <relationshipName>saInquiryReplyDetail_saInquiryDetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>saInquiryReply__c</fullName>
        <label>問い合わせ返事</label>
        <referenceTo>saInquiryReply__c</referenceTo>
        <relationshipLabel>問い合わせ返事詳細</relationshipLabel>
        <relationshipName>saInquiryReplyDetail_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>問い合わせ返事詳細</label>
    <nameField>
        <displayFormat>INQRD-{00000000}</displayFormat>
        <label>問い合わせ返事詳細 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/saDailyReportCtrlTest.cls
@isTest
private class saDailyReportCtrlTest {
	private static saInquiry__c createInquiry(){
		saInquiry__c inq = new saInquiry__c();
		inq.Type__c = 'DAILY_REPORT';
		inq.Status__c = 'Saved';
		inq.ReportName__c = 'Test';
		inq.ValidFrom__c = Date.today().addDays(-2);
		inq.ValidTo__c = Date.today().addDays(2);
		insert inq;
		return inq;
	}

	private static saInquiryReply__c createReply1(Id inqId, Id userId){
		saInquiryReply__c reply = new saInquiryReply__c();
		reply.User__c = userId;
		reply.Status__c = 'REPLY_SAVED';
		reply.DailyReportDate__c = Date.today();
		reply.saInquiry__c = inqId;
		insert reply;
		return reply;
	}
	private static saInquiryReply__c createReply2(Id inqId, Id userId){
		saInquiryReply__c reply = new saInquiryReply__c();
		reply.User__c = userId;
		reply.Status__c = 'REPLY_SAVED';
		reply.DailyReportDate__c = null;
		reply.saInquiry__c = inqId;
		insert reply;
		return reply;
	}

	private static saInquiryDetail__c createInquiryDetail(Id inqId, String replyType) {
		saInquiryDetail__c inqDetail = new saInquiryDetail__c();
		inqDetail.NumberPossibleReplies__c = 2;
		inqDetail.AnswerType__c = replyType;
		inqDetail.QuestionLabel__c = 'Sample Question';
		inqDetail.SortNo__c = math.mod(Datetime.now().millisecond(), 5);
		inqDetail.saInquiry__c = inqId;
		inqDetail.Reply01Label__c = 'Reply 01';
		inqDetail.Reply02Label__c = 'Reply 02';
		insert inqDetail;
		return inqDetail;
	}

	private static saInquiryReplyDetail__c createReplyDetail(Id replyId, Id inqDetailId) {
		saInquiryReplyDetail__c replyDetail = new saInquiryReplyDetail__c();
		replyDetail.saInquiryDetail__c = inqDetailId;
		replyDetail.saInquiryReply__c = replyId;
		replyDetail.ReplyRadioButton__c = 'REPLY_01';
		replyDetail.ReplyCheckbox01__c = true;
		replyDetail.ReplyCheckbox02__c = false;
		insert replyDetail;
		return replyDetail;
	}

	private static saBusinessLocation__c createBusLoca(Id userId) {
		saBusinessLocation__c master = new saBusinessLocation__c();
		master.BusinessLocationName__c = 'Test';
		master.Code__c = 'Test';
		master.IsActive__c = true;
		master.AgencyCode__c = 'Test';
		master.AgencyName__c = 'Test';
		master.SupervisorCode__c = 'Test';
		master.SupervisorName__c = 'Test';
		insert master;

		saBusinessLocationMembers__c member = new saBusinessLocationMembers__c();
		member.User__c = userId;
		member.Type__c = 'PRINCIPAL';
		member.BusinessLocation__c = master.Id;
		insert member;
		return master;
	}

	@isTest static void test_constructor1() {
		saInquiry__c inq = createInquiry();
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.test@kddi.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');
        System.runAs(u) {
        	saBusinessLocation__c buss = createBusLoca(u.Id);

        	PageReference pageRef = Page.saDailyReport;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');

        	//saInquiryReply__c reply1 = createReply1(inq.Id, u.Id);
        	saInquiryReply__c reply2 = createReply2(inq.Id, u.Id);
        	saInquiryDetail__c inqDetail1 = createInquiryDetail(inq.Id, 'CHECKBOX');
        	saInquiryDetail__c inqDetail2 = createInquiryDetail(inq.Id, 'RADIO_BUTTON');
        	saInquiryDetail__c inqDetail3 = createInquiryDetail(inq.Id, 'TEXT');
        	saInquiryDetail__c inqDetail4 = createInquiryDetail(inq.Id, 'NUMBER');
        	saInquiryDetail__c inqDetail5 = createInquiryDetail(inq.Id, 'DECIMAL');
        	saInquiryDetail__c inqDetail6 = createInquiryDetail(inq.Id, 'DATE');
        	saInquiryDetail__c inqDetail7 = createInquiryDetail(inq.Id, 'PERIOD');

        	saInquiryReplyDetail__c replyDetal1 = createReplyDetail(reply2.Id, inqDetail1.Id);
        	saInquiryReplyDetail__c replyDetal2 = createReplyDetail(reply2.Id, inqDetail2.Id);
        	saInquiryReplyDetail__c replyDetal3 = createReplyDetail(reply2.Id, inqDetail3.Id);
        	saInquiryReplyDetail__c replyDetal4 = createReplyDetail(reply2.Id, inqDetail4.Id);
        	saInquiryReplyDetail__c replyDetal5 = createReplyDetail(reply2.Id, inqDetail5.Id);
        	saInquiryReplyDetail__c replyDetal6 = createReplyDetail(reply2.Id, inqDetail6.Id);
        	saInquiryReplyDetail__c replyDetal7 = createReplyDetail(reply2.Id, inqDetail7.Id);

			saDailyReportCtrl ctrl = new saDailyReportCtrl();
			ctrl.idBusinessLocation = buss.Id;
			ctrl.showDayParam1 = String.valueOf(Date.today().day());
			ctrl.getTypeOfScreen();
			ctrl.dummyAction();
			ctrl.redirectIfNecessaryDesktop();
			ctrl.redirectIfNecessaryMobile();
			ctrl.showDayParam1 = String.valueOf(Date.today().day());
			ctrl.iCurrentDay = Date.today().day();
			//ctrl.dCurrentDay = Date.today();
			ctrl.showInquiry();
			ctrl.saveInquiry();
			ctrl.sendInquiry();
			ctrl.sendInquiryConfirm();
			ctrl.saveInquiryPrivate('REPLY_SENT');
			ctrl.showDay();
			ctrl.gotoPreviousMonth();
			ctrl.gotoNextMonth();
			ctrl.getCurrentMonthLabel();
			ctrl.getCurrentDayLabel();
        }

	}
	
	@isTest static void test_constructor2() {
		saInquiry__c inq = createInquiry();
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.standarduser@ezweb.ne.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');
        System.runAs(u) {
        	createBusLoca(u.Id);
        	PageReference pageRef = Page.saDailyReport;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');

        	saInquiryReply__c reply1 = createReply1(inq.Id, u.Id);
        	saInquiryReply__c reply2 = createReply2(inq.Id, u.Id);
        	saInquiryDetail__c inqDetail1 = createInquiryDetail(inq.Id, 'CHECKBOX');
        	saInquiryDetail__c inqDetail2 = createInquiryDetail(inq.Id, 'RADIO_BUTTON');
        	saInquiryDetail__c inqDetail3 = createInquiryDetail(inq.Id, 'TEXT');
        	saInquiryDetail__c inqDetail4 = createInquiryDetail(inq.Id, 'NUMBER');
        	saInquiryDetail__c inqDetail5 = createInquiryDetail(inq.Id, 'DECIMAL');
        	saInquiryDetail__c inqDetail6 = createInquiryDetail(inq.Id, 'DATE');
        	saInquiryDetail__c inqDetail7 = createInquiryDetail(inq.Id, 'PERIOD');

        	saInquiryReplyDetail__c replyDetal1 = createReplyDetail(reply1.Id, inqDetail1.Id);
        	saInquiryReplyDetail__c replyDetal2 = createReplyDetail(reply1.Id, inqDetail2.Id);
        	saInquiryReplyDetail__c replyDetal3 = createReplyDetail(reply1.Id, inqDetail3.Id);
        	saInquiryReplyDetail__c replyDetal4 = createReplyDetail(reply1.Id, inqDetail4.Id);
        	saInquiryReplyDetail__c replyDetal5 = createReplyDetail(reply1.Id, inqDetail5.Id);
        	saInquiryReplyDetail__c replyDetal6 = createReplyDetail(reply1.Id, inqDetail6.Id);
        	saInquiryReplyDetail__c replyDetal7 = createReplyDetail(reply1.Id, inqDetail7.Id);

			saDailyReportCtrl ctrl = new saDailyReportCtrl();
			ctrl.showDayParam1 = String.valueOf(Date.today().day());
			ctrl.iCurrentDay = Date.today().day();
			ctrl.showInquiry();
			ctrl.saveInquiry();
			ctrl.sendInquiry();
			ctrl.sendInquiryConfirm();
			ctrl.saveInquiryPrivate('REPLY_SENT');
        }
	}
	
	@isTest static void test_comments1() {
		saInquiry__c inq = createInquiry();
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.standarduser@ezweb.ne.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');
        System.runAs(u) {
        	createBusLoca(u.Id);
        	PageReference pageRef = Page.saDailyReport;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');

        	saInquiryReply__c reply1 = createReply1(inq.Id, u.Id);
        	saInquiryReply__c reply2 = createReply2(inq.Id, u.Id);
        	saInquiryDetail__c inqDetail1 = createInquiryDetail(inq.Id, 'CHECKBOX');
        	saInquiryDetail__c inqDetail2 = createInquiryDetail(inq.Id, 'RADIO_BUTTON');
        	saInquiryDetail__c inqDetail3 = createInquiryDetail(inq.Id, 'TEXT');
        	saInquiryDetail__c inqDetail4 = createInquiryDetail(inq.Id, 'NUMBER');
        	saInquiryDetail__c inqDetail5 = createInquiryDetail(inq.Id, 'DECIMAL');
        	saInquiryDetail__c inqDetail6 = createInquiryDetail(inq.Id, 'DATE');
        	saInquiryDetail__c inqDetail7 = createInquiryDetail(inq.Id, 'PERIOD');

        	saInquiryReplyDetail__c replyDetal1 = createReplyDetail(reply1.Id, inqDetail1.Id);
        	saInquiryReplyDetail__c replyDetal2 = createReplyDetail(reply1.Id, inqDetail2.Id);
        	saInquiryReplyDetail__c replyDetal3 = createReplyDetail(reply1.Id, inqDetail3.Id);
        	saInquiryReplyDetail__c replyDetal4 = createReplyDetail(reply1.Id, inqDetail4.Id);
        	saInquiryReplyDetail__c replyDetal5 = createReplyDetail(reply1.Id, inqDetail5.Id);
        	saInquiryReplyDetail__c replyDetal6 = createReplyDetail(reply1.Id, inqDetail6.Id);
        	saInquiryReplyDetail__c replyDetal7 = createReplyDetail(reply1.Id, inqDetail7.Id);

			saDailyReportCtrl ctrl = new saDailyReportCtrl();
			ctrl.showDayParam1 = String.valueOf(Date.today().day());
			ctrl.iCurrentDay = Date.today().day();
			ctrl.showPreviewInquiry();
			ctrl.showInquiry();
			ctrl.saveInquiry();
			ctrl.sendInquiry();
			//ctrl.sendInquiryConfirm();
			//ctrl.saveInquiryPrivate('REPLY_SENT');
			Test.startTest();
			ctrl.comment1 = 'This is comment 1.';
			ctrl.upsertComment1();
			ctrl.deleteComment1();
			ctrl.comment2 = 'This is comment 2.';
			ctrl.upsertComment2();
			ctrl.deleteComment2();
			ctrl.comment3 = 'This is comment 3.';
			ctrl.upsertComment3();
			ctrl.deleteComment3();
			ctrl.comment4 = 'This is comment 4.';
			ctrl.upsertComment4();
			ctrl.deleteComment4();
			ctrl.comment5 = 'This is comment 5.';
			ctrl.upsertComment5();
			ctrl.deleteComment5();
			ctrl.comment6 = 'This is comment 6.';
			ctrl.upsertComment6();
			ctrl.deleteComment6();
			ctrl.comment7 = 'This is comment 7.';
			ctrl.upsertComment7();
			ctrl.deleteComment7();
			ctrl.comment8 = 'This is comment 8.';
			ctrl.upsertComment8();
			ctrl.deleteComment8();
			ctrl.comment9 = 'This is comment 9.';
			ctrl.upsertComment9();
			ctrl.deleteComment9();
			ctrl.comment10 = 'This is comment 10.';
			ctrl.upsertComment10();
			ctrl.deleteComment10();

			Test.stopTest();
        }
		
	} 
	
	@isTest static void test_comments2() {
		saInquiry__c inq = createInquiry();
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.standarduser@ezweb.ne.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='duchm@testKDDI.com');
        System.runAs(u) {
        	createBusLoca(u.Id);
        	PageReference pageRef = Page.saDailyReport;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');

        	saInquiryReply__c reply1 = createReply1(inq.Id, u.Id);
        	saInquiryReply__c reply2 = createReply2(inq.Id, u.Id);
        	saInquiryDetail__c inqDetail1 = createInquiryDetail(inq.Id, 'CHECKBOX');
        	saInquiryDetail__c inqDetail2 = createInquiryDetail(inq.Id, 'RADIO_BUTTON');
        	saInquiryDetail__c inqDetail3 = createInquiryDetail(inq.Id, 'TEXT');
        	saInquiryDetail__c inqDetail4 = createInquiryDetail(inq.Id, 'NUMBER');
        	saInquiryDetail__c inqDetail5 = createInquiryDetail(inq.Id, 'DECIMAL');
        	saInquiryDetail__c inqDetail6 = createInquiryDetail(inq.Id, 'DATE');
        	saInquiryDetail__c inqDetail7 = createInquiryDetail(inq.Id, 'PERIOD');

        	saInquiryReplyDetail__c replyDetal1 = createReplyDetail(reply1.Id, inqDetail1.Id);
        	saInquiryReplyDetail__c replyDetal2 = createReplyDetail(reply1.Id, inqDetail2.Id);
        	saInquiryReplyDetail__c replyDetal3 = createReplyDetail(reply1.Id, inqDetail3.Id);
        	saInquiryReplyDetail__c replyDetal4 = createReplyDetail(reply1.Id, inqDetail4.Id);
        	saInquiryReplyDetail__c replyDetal5 = createReplyDetail(reply1.Id, inqDetail5.Id);
        	saInquiryReplyDetail__c replyDetal6 = createReplyDetail(reply1.Id, inqDetail6.Id);
        	saInquiryReplyDetail__c replyDetal7 = createReplyDetail(reply1.Id, inqDetail7.Id);

			saDailyReportCtrl ctrl = new saDailyReportCtrl();
			ctrl.showDayParam1 = String.valueOf(Date.today().day());
			ctrl.iCurrentDay = Date.today().day();
			ctrl.showInquiry();
			ctrl.saveInquiry();
			ctrl.sendInquiry();
			//ctrl.sendInquiryConfirm();
			//ctrl.saveInquiryPrivate('REPLY_SENT');
			Test.startTest();
			ctrl.comment11 = 'This is comment 11.';
			ctrl.upsertComment11();
			ctrl.deleteComment11();
			ctrl.comment12 = 'This is comment 12.';
			ctrl.upsertComment12();
			ctrl.deleteComment12();
			ctrl.comment13 = 'This is comment 13.';
			ctrl.upsertComment13();
			ctrl.deleteComment13();
			ctrl.comment14 = 'This is comment 14.';
			ctrl.upsertComment14();
			ctrl.deleteComment14();
			ctrl.comment15 = 'This is comment 15.';
			ctrl.upsertComment15();
			ctrl.deleteComment15();
			ctrl.comment16 = 'This is comment 16.';
			ctrl.upsertComment16();
			ctrl.deleteComment16();
			ctrl.comment17 = 'This is comment 17.';
			ctrl.upsertComment17();
			ctrl.deleteComment17();
			ctrl.comment18 = 'This is comment 18.';
			ctrl.upsertComment18();
			ctrl.deleteComment18();
			ctrl.comment19 = 'This is comment 19.';
			ctrl.upsertComment19();
			ctrl.deleteComment19();
			ctrl.comment20 = 'This is comment 20.';
			ctrl.upsertComment20();
			ctrl.deleteComment20();
			Test.stopTest();
        }
		
	} 
	
}