src/objects/saBusinessLocation__c.object
<CustomObject>
    <label>拠点</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>saBusinessLocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/saInquiry__c.object
<CustomObject>
    <fields>
        <fullName>ReportName__c</fullName>
        <label>フォーム名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>TemporarySaved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>DAILY_REPORT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SURVEY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU_HEARING</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidFrom__c</fullName>
        <label>運用From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ValidTo__c</fullName>
        <label>運用To</label>
        <type>Date</type>
    </fields>
    <label>問い合わせ</label>
    <nameField>
        <displayFormat>INQ-{00000000}</displayFormat>
        <label>問い合わせ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/saInquiryDetail__c.object
<CustomObject>
    <fields>
        <fullName>AnswerType__c</fullName>
        <label>AnswerType</label>
        <picklist>
            <picklistValues>
                <fullName>TEXT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NUMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DECIMAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RADIO_BUTTON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHECKBOX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERIOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LABEL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NumberPossibleReplies__c</fullName>
        <label>NumberPossibleReplies</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>QuestionLabel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply01Label__c</fullName>
        <label>Reply01Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply02Label__c</fullName>
        <label>Reply02Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>SortNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>saInquiry__c</fullName>
        <label>問い合わせ</label>
        <referenceTo>saInquiry__c</referenceTo>
        <relationshipLabel>問い合わせ詳細</relationshipLabel>
        <relationshipName>saInquiryDetail_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>問い合わせ詳細</label>
    <nameField>
        <displayFormat>INQD-{00000000}</displayFormat>
        <label>問い合わせ詳細 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/saInquiryReply__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>WAITING_REPLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_SAVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REPLY_SENT</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>saBusinessLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>拠点</label>
        <referenceTo>saBusinessLocation__c</referenceTo>
        <relationshipLabel>問い合わせ返事</relationshipLabel>
        <relationshipName>saInquiryReply_saBusinessLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>saInquiry__c</fullName>
        <label>問い合わせ</label>
        <referenceTo>saInquiry__c</referenceTo>
        <relationshipLabel>問い合わせ返事</relationshipLabel>
        <relationshipName>saInquiryReply_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>問い合わせ返事</label>
    <nameField>
        <displayFormat>INQR-{00000000}</displayFormat>
        <label>問い合わせ返事 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/saInquiryReplyDetail__c.object
<CustomObject>
    <fields>
        <fullName>saInquiryDetail__c</fullName>
        <label>問い合わせ詳細</label>
        <referenceTo>saInquiryDetail__c</referenceTo>
        <relationshipLabel>問い合わせ返事詳細</relationshipLabel>
        <relationshipName>saInquiryReplyDetail_saInquiryDetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>saInquiryReply__c</fullName>
        <label>問い合わせ返事</label>
        <referenceTo>saInquiryReply__c</referenceTo>
        <relationshipLabel>問い合わせ返事詳細</relationshipLabel>
        <relationshipName>saInquiryReplyDetail_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>問い合わせ返事詳細</label>
    <nameField>
        <displayFormat>INQRD-{00000000}</displayFormat>
        <label>問い合わせ返事詳細 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/auHearingListForAdminCtlTest.cls
@isTest
private class auHearingListForAdminCtlTest {
    
    private static saInquiry__c createInquiry(){
		saInquiry__c inq = new saInquiry__c();
		inq.Type__c = 'DAILY_REPORT';
		inq.Status__c = 'Saved';
		inq.ReportName__c = 'Test';
		inq.ValidFrom__c = Date.today().addDays(-2);
		inq.ValidTo__c = Date.today().addDays(2);
		insert inq;
		return inq;
	}

	private static saInquiryDetail__c createInquiryDetail(Id inqId, String replyType) {
		saInquiryDetail__c inqDetail = new saInquiryDetail__c();
		inqDetail.NumberPossibleReplies__c = 2;
		inqDetail.AnswerType__c = replyType;
		inqDetail.QuestionLabel__c = 'Sample Question';
		inqDetail.SortNo__c = math.mod(Datetime.now().millisecond(), 5);
		inqDetail.saInquiry__c = inqId;
		inqDetail.Reply01Label__c = 'Reply 01';
		inqDetail.Reply02Label__c = 'Reply 02';
		insert inqDetail;
		return inqDetail;
	}

    @isTest static void searchTest() {
		
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.test@kddi.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='tremy@testKDDI.com');
           
        saInquiry__c inq = createInquiry();
        
		PageReference pageRef = Page.auHearingListForAdmin;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');
        
        System.runAs(u) {
        	//saBusinessLocation__c buss = createBusLoca(u.Id);
        	saInquiryDetail__c inqDetail1 = createInquiryDetail(inq.Id, 'CHECKBOX');
        	saInquiryDetail__c inqDetail2 = createInquiryDetail(inq.Id, 'RADIO_BUTTON');
        	saInquiryDetail__c inqDetail3 = createInquiryDetail(inq.Id, 'TEXT');
        	saInquiryDetail__c inqDetail4 = createInquiryDetail(inq.Id, 'NUMBER');
        	saInquiryDetail__c inqDetail5 = createInquiryDetail(inq.Id, 'DECIMAL');
        	saInquiryDetail__c inqDetail6 = createInquiryDetail(inq.Id, 'DATE');
        	saInquiryDetail__c inqDetail7 = createInquiryDetail(inq.Id, 'PERIOD');
        	
        	//saInquiryReply__c reply = createReply(inq.Id, u.Id);

        	/*saInquiryReplyDetail__c replyDetail1 = createReplyDetail(reply.Id, inqDetail1.Id);
        	saInquiryReplyDetail__c replyDetail2 = createReplyDetail(reply.Id, inqDetail2.Id);
        	saInquiryReplyDetail__c replyDetail3 = createReplyDetail(reply.Id, inqDetail3.Id);
        	saInquiryReplyDetail__c replyDetail4 = createReplyDetail(reply.Id, inqDetail4.Id);
        	saInquiryReplyDetail__c replyDetail5 = createReplyDetail(reply.Id, inqDetail5.Id);
        	saInquiryReplyDetail__c replyDetail6 = createReplyDetail(reply.Id, inqDetail6.Id);
        	saInquiryReplyDetail__c replyDetail7 = createReplyDetail(reply.Id, inqDetail7.Id);*/

        	auHearingListForAdminCtl ctrl = new auHearingListForAdminCtl();
        	ctrl.searchItemClear();
        	ctrl.recordSearch();
        	//system.debug('SSC : '+ctrl.getRecords().size());
        	//System.assertEquals(ctrl.getRecords().size()>0,true);
        	//ctrl.currentInquiryReplyId = reply2.Id;

        }
	}
	
}