src/objects/saReport__c.object
<CustomObject>
    <fields>
        <fullName>Report_body__c</fullName>
        <label>Report body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAApprover1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAApprover1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>saReport1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publish</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>saReport</label>
    <nameField>
        <displayFormat>SA_Report-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Hierarchical_Code_1__c</fullName>
        <label>Hierarchical Code 1</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_3__c</fullName>
        <label>第3階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_4__c</fullName>
        <label>第4階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Label_5__c</fullName>
        <label>第5階層名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAApprover1__c</fullName>
        <label>SAApprover1</label>
        <relationshipName>SA_SAApprover1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/saHomeCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class saHomeCtrlTest {

	private static saReport__c createReport(Id userId, String status){
		saReport__c rep = new sareport__c();
		rep.Subject__c = 'Test';
		rep.SAApprover1__c = userId;
		rep.State__c = status;
		rep.Report_body__c = 'Test';
		insert rep;
		return rep;
	}

    @isTest(SeeAllData=true) 
    static void constructorTest() {
		
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
		User u = new User(Alias = 'standt', Email='dummy.test1@kddi.jp', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Tokyo', UserName='tremy1@testKDDI.com', Hierarchical_Code_1__c='010K0J',
            Hierarchical_Label_3__c='Label3',Hierarchical_Label_4__c='Label4',Hierarchical_Label_5__c='Label5');
	    	
	    insert u;  
		System.runAs(u) {   
		    	
				PageReference pageRef = Page.saHome;
				Test.setCurrentPage(pageRef);
				ApexPages.currentPage().getHeaders().put('User-Agent', 'ipad');
	        
	        	saHomeCtrl ctrl = new saHomeCtrl();
	        	
	        	ctrl.showRankingDetail();
	        	ctrl.displayMoreMostSeenReports();
	        	ctrl.displayMoreMostRecentReports();
	        	
	        	saReport__c report = createReport(u.Id, saConstantCmn.SA_REPORT_STATE_PUBLISHED);
	        	System.currentPageReference().getParameters().put('reportId', report.Id);
	        	ctrl.redirectToConcernedReport();
	        	
	        	ctrl.goToReportPages();
	        	ctrl.redirectIfNecessaryMobile();
	        	ctrl.redirectIfNecessaryDesktop();
	        	
	        	Integer testTypeOfScreen = ctrl.getTypeOfScreen();
	        	Double testOffset = ctrl.offset;
	        	ctrl.dummyAction();
	        	
	    }

	}
}